# Generated by Django 5.0.6 on 2026-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_attainment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indirect_attainment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_attainment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attainment_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
