# Generated by Django 5.0.6 on 2026-08-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attainments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attainment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='attainment',
            name='course_outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attainment', to='courses.courseoutcome'),
        ),
    ]
