# Generated by Django 6.1 on 2026-08-26 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainments', '0004_alter_programattainment_po_key'),
        ('courses', '0006_course_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCoAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30)),
                ('nba_code', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=6)),
                ('co_code', models.CharField(max_length=20)),
                ('attainment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_co_attainments', to=settings.AUTH_USER_MODEL)),
                ('source_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_co_attainments', to='courses.course')),
            ],
            options={
                'ordering': ['-academic_year', 'co_code'],
                'constraints': [models.UniqueConstraint(fields=('course_code', 'academic_year', 'semester', 'co_code'), name='unique_historical_co_attainment')],
            },
        ),
    ]
