# Generated by Django 5.0.6 on 2026-09-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attainments", "0007_seed_previous_year_for_sample_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="attainment",
            name="breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
