# Generated by Django 6.1 on 2026-08-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('courses', '0006_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('course', 'roll_number')},
        ),
    ]
