# Generated by Django 5.0.6 on 2026-09-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_student_unique_per_course"),
        ("courses", "0006_course_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["roll_number"]},
        ),
        migrations.AddField(
            model_name="assessment",
            name="appeared",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assessment",
            name="exam_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="assessment",
            name="target_percent",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="assessment",
            name="total_students",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assessment",
            name="use_ceiling",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T2", "T2"),
                    ("T3", "T3"),
                    ("TA", "TA (Attendance / Project / Assignment)"),
                    ("FEEDBACK", "Course Exit Feedback"),
                    ("ASSIGNMENT", "Assignment"),
                    ("ATTENDANCE", "Attendance"),
                    ("PROJECT", "Project"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="max_marks",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="marks_obtained",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=80)),
                (
                    "max_marks",
                    models.DecimalField(decimal_places=2, default=5, max_digits=6),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "course_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_questions",
                        to="courses.courseoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("assessment", "key")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="studentmark",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentmark",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="assessments.assessmentquestion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentmark",
            unique_together={("assessment", "student", "question")},
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=8)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_bands",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["min_marks", "id"],
            },
        ),
    ]
