# Generated by Django 5.0.6 on 2026-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoPoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_key', models.CharField(choices=[('PO1', 'PO1'), ('PO2', 'PO2'), ('PO3', 'PO3'), ('PSO1', 'PSO1'), ('PSO2', 'PSO2')], max_length=5)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('nba_code', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=6)),
                ('academic_year', models.CharField(help_text='e.g. 2025-26', max_length=9)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-academic_year', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('cognitive_level', models.CharField(choices=[('REMEMBER', 'Remember (C1)'), ('UNDERSTAND', 'Understand (C2)'), ('APPLY', 'Apply (C3)'), ('ANALYZE', 'Analyze (C4)'), ('EVALUATE', 'Evaluate (C5)'), ('CREATE', 'Create / Design (C6)')], max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
