# Generated by Django 5.0.6 on 2026-08-16 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='courses.courseoutcome'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='courseoutcome',
            unique_together={('course', 'co_code')},
        ),
        migrations.AlterUniqueTogether(
            name='copomapping',
            unique_together={('course_outcome', 'po_key')},
        ),
    ]
