# Generated by Django 5.0.6 on 2026-08-24 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Text Book'), ('REFERENCE', 'Reference Book')], max_length=12)),
                ('title', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LectureModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('serial_no', models.CharField(blank=True, max_length=10)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('topics', models.TextField(blank=True)),
                ('lectures', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator_names',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='doc_title',
            field=models.CharField(default='Detailed Syllabus', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='end_sem_marks',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='institute_sub',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='logo_fallback',
            field=models.CharField(default='LOGO', max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='pbl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='t1_marks',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='t2_marks',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='ta_marks',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='course',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(help_text='Session, e.g. 2024-25 or 2024-2025', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'academic_year', 'faculty'), name='unique_course_per_faculty_session'),
        ),
        migrations.AddField(
            model_name='coursebook',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lecturemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
    ]
