# Generated by Django 5.0.6 on 2026-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_program_po_pso_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
