# Generated by Django 6.1 on 2026-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseoutcome_description_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. Department of CSE & IT', max_length=255),
        ),
    ]
