# Generated by Django 6.1 on 2026-08-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_label', models.CharField(blank=True, max_length=80)),
                ('watermark_text', models.CharField(default='OPENING', max_length=80)),
                ('gaps_nil', models.BooleanField(default=True)),
                ('gaps_rows', models.JSONField(blank=True, default=list)),
                ('mods_nil', models.BooleanField(default=True)),
                ('mods_rows', models.JSONField(blank=True, default=list)),
                ('co_actions', models.JSONField(blank=True, default=dict)),
                ('teaching_methods', models.JSONField(blank=True, default=list)),
                ('teaching_other', models.CharField(blank=True, max_length=500)),
                ('weak_strategies', models.JSONField(blank=True, default=list)),
                ('weak_other', models.CharField(blank=True, max_length=500)),
                ('bright_strategies', models.JSONField(blank=True, default=list)),
                ('bright_other', models.CharField(blank=True, max_length=500)),
                ('eval_strategies', models.JSONField(blank=True, default=list)),
                ('eval_other', models.CharField(blank=True, max_length=500)),
                ('guidelines', models.JSONField(blank=True, default=list)),
                ('efforts_rows', models.JSONField(blank=True, default=list)),
                ('impact_points', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_report', to='courses.course')),
            ],
        ),
    ]
