# Generated by Django 6.1 on 2026-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingreport',
            name='co_targets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
